# Generated by Django 6.0.2 on 2026-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                    ),
                ),
                ("emergency_call", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Hoạt động"),
                            ("inactive", "Không hoạt động"),
                            ("deleted", "Đã xóa"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "students",
                "ordering": ["-created_at"],
            },
        ),
    ]
