# Generated by Django 6.0.2 on 2026-02-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="birth_year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Năm sinh", null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.CharField(blank=True, help_text="Trường học", max_length=200),
        ),
    ]
