# Generated by Django 6.0.2 on 2026-02-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Quản trị viên"),
                    ("teacher", "Giáo viên"),
                    ("assistant", "Trợ giảng"),
                    ("parent", "Phụ huynh"),
                ],
                default="teacher",
                max_length=20,
            ),
        ),
    ]
