# Generated by Django 6.0.2 on 2026-02-26 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "subjects",
                "ordering": ["subject_name"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_code", models.CharField(max_length=50, unique=True)),
                ("class_name", models.CharField(max_length=200)),
                (
                    "schedule_days",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2,4,6' for Mon=1, Sun=7",
                        max_length=50,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("room", models.CharField(blank=True, max_length=100)),
                ("max_students", models.IntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assistants",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "assistant"},
                        related_name="assistant_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="classes.subject",
                    ),
                ),
            ],
            options={
                "db_table": "classes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Hoạt động"), ("dropped", "Đã rời lớp")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("dropped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_enrolled",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="classes.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "enrollments",
                "ordering": ["-enrolled_at"],
                "unique_together": {("student", "class_enrolled")},
            },
        ),
        migrations.CreateModel(
            name="ParentStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Cha"),
                            ("mother", "Mẹ"),
                            ("guardian", "Người giám hộ"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "parent_student",
                "unique_together": {("parent", "student")},
            },
        ),
    ]
