# Generated by Django 6.0.2 on 2026-03-15 13:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=100, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                    ),
                ),
                (
                    "birth_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Năm sinh", null=True
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, help_text="Trường học", max_length=200
                    ),
                ),
                ("emergency_call", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Đang học"), ("inactive", "Nghỉ")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "students",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalStudent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(blank=True, db_index=True, max_length=100)),
                ("full_name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                    ),
                ),
                (
                    "birth_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Năm sinh", null=True
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True, help_text="Trường học", max_length=200
                    ),
                ),
                ("emergency_call", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Đang học"), ("inactive", "Nghỉ")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical student",
                "verbose_name_plural": "historical students",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
