# Generated by Django 6.0.2 on 2026-03-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_status_historicalstudent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstudent",
            name="status",
            field=models.CharField(
                choices=[("active", "Đang học"), ("inactive", "Nghỉ")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[("active", "Đang học"), ("inactive", "Nghỉ")],
                default="active",
                max_length=20,
            ),
        ),
    ]
