# Generated by Django 6.0.2 on 2026-03-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_historicalstudent_status_alter_student_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstudent",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="historicalstudent",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="restored_at",
        ),
    ]
