# Generated by Django 6.0.2 on 2026-02-26 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tuition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tuition_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Theo tháng"),
                            ("course", "Theo khóa học"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True, help_text="YYYY-MM format", max_length=7
                    ),
                ),
                ("course_name", models.CharField(blank=True, max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                ("paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("transfer", "Chuyển khoản"),
                            ("card", "Thẻ"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuitions",
                        to="classes.enrollment",
                    ),
                ),
            ],
            options={
                "db_table": "tuition",
                "ordering": ["-created_at"],
                "unique_together": {
                    ("enrollment", "course_name"),
                    ("enrollment", "month"),
                },
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_at", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("transfer", "Chuyển khoản"),
                            ("card", "Thẻ"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "tuition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_histories",
                        to="payments.tuition",
                    ),
                ),
            ],
            options={
                "db_table": "payment_histories",
                "ordering": ["-paid_at"],
            },
        ),
    ]
