# Generated by Django 6.0.2 on 2026-03-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymenthistory',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='historicaltuition',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='payment_method',
        ),
    ]
