# Generated by Django 6.0.2 on 2026-03-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_class_status_historicalclass_status_and_more"),
        ("payments", "0002_historicalpaymenthistory_historicaltuition"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tuition",
            unique_together={("enrollment", "month")},
        ),
    ]
