# Generated by Django 6.0.2 on 2026-03-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
