# Generated by Django 6.0.2 on 2026-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_historicalclass_historicalenrollment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalclass",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalclass",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
