# Generated by Django 6.0.2 on 2026-03-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_class_end_date_class_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="tuition_fee",
            field=models.IntegerField(
                blank=True, help_text="Học phí của lớp (VND)", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalclass",
            name="tuition_fee",
            field=models.IntegerField(
                blank=True, help_text="Học phí của lớp (VND)", null=True
            ),
        ),
    ]
