# Generated by Django 6.0.2 on 2026-03-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0004_class_tuition_fee_historicalclass_tuition_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chưa bắt đầu"),
                    ("active", "Khai giảng"),
                    ("completed", "Kết thúc"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalclass",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chưa bắt đầu"),
                    ("active", "Khai giảng"),
                    ("completed", "Kết thúc"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Hoạt động"),
                    ("completed", "Hoàn thành"),
                    ("dropped", "Đã rời lớp"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Hoạt động"),
                    ("completed", "Hoàn thành"),
                    ("dropped", "Đã rời lớp"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
